---
- name: Install Measurers
  hosts: all

  tasks:
    - name: Install ping_pong_measurer_rclex
      shell: |
        rm -rf ping_pong_measurer_rclex
        git clone -b v1.1.0 https://github.com/b5g-ex/ping_pong_measurer_rclex.git
        cd ping_pong_measurer_rclex
        bash -ic "mix do deps.get, rclex.gen.msgs, compile && exit"

    - name: Install ping_pong_measurer_ros2
      shell: |
        rm -rf ros2_ws
        mkdir -p ros2_ws/src
        git clone -b v1.1.0 https://github.com/b5g-ex/ping_pong_measurer_ros2.git ros2_ws/src/ping_pong_measurer
        cd ros2_ws && ln -sf src/ping_pong_measurer/Makefile Makefile

    - name: Install os_info_measurer
      shell: |
        rm -rf os_info_measurer
        git clone -b v0.1.1 https://github.com/b5g-ex/os_info_measurer.git
        cd os_info_measurer
        bash -ic "mix do deps.get, compile && exit"
